### ISSUE TITLE
Bird tracking dataset

### ISSUE THREAD

**Issue by peterdesmet** [inbo/dwc-event-workshop#1]
- Small dataset: https://doi.org/10.5281/zenodo.10053903
- Read with `dataset <- frictionless::read_package("https://zenodo.org/records/10053903/files/datapackage.json")` 
- DwC transformation to **occurrence data** is done with `movepub::write_dwc()`.
  - High level transformation is explained at https://inbo.github.io/movepub/reference/write_dwc.html#data
  - @sangovae is currently updating this transformation to dplyr in: https://github.com/inbo/movepub/pull/63
  - GPS data are reduced to one per hour as machine observations
  - Deployments (in reference data) are used as `parentEventID` for observations
  - Reference data are also used as source for human observations (e.g. capture)

Todo:

- [ ] Create schema of current mapping (occurrence core)
- [ ] Create schema of event core mapping
- [ ] Create schema of ideal mapping
- [ ] Create transformations of raw dataset to the above mappings
